//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceASU1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Records
    {
        public int id { get; set; }
        public Nullable<int> idService { get; set; }
        public Nullable<int> idClient { get; set; }
        public System.DateTime DateTimeStart { get; set; }

        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }

    }
}
